apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: ClusterIP
  ports:
  - port: 8888         # Port sur lequel le service est exposé
    targetPort: 8888   # Port sur lequel le conteneur écoute
    protocol: TCP
  selector:
    app: wil-playground


