apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
spec:
  ports:
  - port: 80          # Port sur lequel le service est exposé
    targetPort: 8888  # Port sur lequel l'application écoute dans le conteneur
    protocol: TCP
  selector:
    app: wil-playground
  type: ClusterIP
