apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: wil-playground
  ports:
    - port: 8888           # Port du service
      targetPort: 8888     # Port du conteneur
      protocol: TCP
