apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  ports:
  - port: 80        # Port sur lequel le service écoute
    targetPort: 80  # Port sur lequel le conteneur écoute
    protocol: TCP
  selector:
    app: wil-playground
